language: cpp
matrix:
  # Linux Native
  - os: linux
    compiler: gcc
    env: ARCH=native META_USE_CXX11=ON
  - os: linux
    compiler: gcc
    env: ARCH=native META_USE_CXX11=OFF
  - os: linux
    compiler: clang
    env: ARCH=native META_USE_CXX11=ON
  - os: linux
    compiler: clang
    env: ARCH=native META_USE_CXX11=OFF
  # Raspbian/ARM
  - os: linux
    compiler: gcc
    env: ARCH=arm META_USE_CXX11=ON
  - os: linux
    compiler: gcc
    env: ARCH=arm META_USE_CXX11=OFF
  - os: linux
    compiler: clang
    env: ARCH=arm META_USE_CXX11=ON
  - os: linux
    compiler: clang
    env: ARCH=arm META_USE_CXX11=OFF
  # OS X
  - os: osx
    compiler: gcc
    env: ARCH=native META_USE_CXX11=ON
  - os: osx
    compiler: gcc
    env: ARCH=native META_USE_CXX11=OFF
  - os: osx
    compiler: clang
    env: ARCH=native META_USE_CXX11=ON
  - os: osx
    compiler: clang
    env: ARCH=native META_USE_CXX11=OFF
script:
  - "bash -ex ./travis/run.sh"
