before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install libcppunit-dev"
script:
  - "autoreconf -siv"
  - "mkdir build && cd build"
  - "../configure --enable-static --disable-shared"
  - "make distcheck"
