before_install:
  - "sudo apt-get update -qq"
install:
  - "sudo apt-get install libcppunit-dev clang cmake"
script:
  - "mkdir build && cd build"
  - "cmake -DMETA_USE_CXX11=${META_USE_CXX11} .."
  - "make testsuite && ./testsuite"
env:
  - CXX=g++ CC=gcc META_USE_CXX11=ON
  - CXX=clang++ CC=clang META_USE_CXX11=ON
  - CXX=g++ CC=gcc META_USE_CXX11=OFF
  - CXX=clang++ CC=clang META_USE_CXX11=OFF
