language: cpp
matrix:
  include:
    # Clang/Linux/native
    - os: linux
      compiler: clang
      env: ARCH=native META_USE_CXX11=ON
    - os: linux
      compiler: clang
      env: ARCH=native META_USE_CXX11=OFF
    # GCC/Linux/native
    - os: linux
      compiler: gcc
      env: ARCH=native META_USE_CXX11=ON
    - os: linux
      compiler: gcc
      env: ARCH=native META_USE_CXX11=OFF
    # Clang/OSX/native
    - os: osx
      compiler: clang
      env: ARCH=native META_USE_CXX11=ON
    - os: osx
      compiler: clang
      env: ARCH=native META_USE_CXX11=OFF
    # GCC/OSX/native
    - os: osx
      compiler: gcc
      env: ARCH=native META_USE_CXX11=ON
    - os: osx
      compiler: gcc
      env: ARCH=native META_USE_CXX11=OFF
    # GCC/Linux/arm
    - os: linux
      compiler: gcc
      env: ARCH=arm META_USE_CXX11=ON
    - os: linux
      compiler: gcc
      env: ARCH=arm META_USE_CXX11=OFF
    # GCC/Linux/mips
    - os: linux
      compiler: gcc
      env: ARCH=mips META_USE_CXX11=ON
    - os: linux
      compiler: gcc
      env: ARCH=mips META_USE_CXX11=OFF
script:
  - "bash -ex ./travis/run.sh"
