before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install libcppunit-dev clang"
script:
  - "autoreconf -siv"
  - "mkdir build && cd build"
  - "../configure --enable-static --disable-shared"
  - "make distcheck"
env:
  - CXX=g++
  - CXX=clang++
