language: cpp
matrix:
  include:
    # Clang/Linux/native
    # We test both with and without C++11 features
    - os: linux
      compiler: clang
      env: ARCH=native META_USE_CXX11=ON
    - os: linux
      compiler: clang
      env: ARCH=native META_USE_CXX11=OFF
    # GCC/Linux/native
    # We test both with and without C++11 features
    - os: linux
      compiler: gcc
      env: ARCH=native META_USE_CXX11=ON
    - os: linux
      compiler: gcc
      env: ARCH=native META_USE_CXX11=OFF
    # Clang/OSX/native
    # We test only with C++11 features - without was already verified on Linux
    - os: osx
      compiler: clang
      env: ARCH=native META_USE_CXX11=ON
    # GCC/OSX/native
    # We test only with C++11 features - without was already verified on Linux
    - os: osx
      compiler: gcc
      env: ARCH=native META_USE_CXX11=ON
    # GCC/Linux/arm
    # We test only with C++11 features - without was already verified on Linux
    - os: linux
      compiler: gcc
      env: ARCH=arm META_USE_CXX11=ON
    # GCC/Linux/mips
    # We test only with C++11 features - without was already verified on Linux
    - os: linux
      compiler: gcc
      env: ARCH=mips META_USE_CXX11=ON
#script:
#  - "bash -ex ./travis/run.sh"
