language: cpp
matrix:
  include:
    # Clang/Linux/x86_64
    # We test both with and without C++11 features
    - os: linux
      compiler: clang
      env: ARCH=x86_64 META_USE_CXX11=ON
    - os: linux
      compiler: clang
      env: ARCH=x86_64 META_USE_CXX11=OFF
    # GCC/Linux/x86_64
    # We test both with and without C++11 features
    - os: linux
      compiler: gcc
      env: ARCH=x86_64 META_USE_CXX11=ON
    - os: linux
      compiler: gcc
      env: ARCH=x86_64 META_USE_CXX11=OFF
    # Clang/OSX/x86_64
    # We test only with C++11 features - without was already verified on Linux
    - os: osx
      compiler: clang
      env: ARCH=x86_64 META_USE_CXX11=ON
    # GCC/OSX/x86_64
    # We test only with C++11 features - without was already verified on Linux
    - os: osx
      compiler: gcc
      env: ARCH=x86_64 META_USE_CXX11=ON
    # GCC/Linux/armhf
    # We test only with C++11 features - without was already verified on Linux
    - os: linux
      compiler: gcc
      env: ARCH=armhf META_USE_CXX11=ON
    # GCC/Linux/mips
    # We test only with C++11 features - without was already verified on Linux
    - os: linux
      compiler: gcc
      env: ARCH=mips META_USE_CXX11=ON
script:
  - bash -ex ./build.sh "${ARCH}" "${TRAVIS_OS_NAME}" "${TRAVIS_BUILD_DIR}"
