language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - ARCH=native META_USE_CXX11=ON
  - ARCH=native META_USE_CXX11=OFF
  - ARCH=arm META_USE_CXX11=ON
  - ARCH=arm META_USE_CXX11=OFF
matrix:
  exclude:
    - os: osx
      env: ARCH=arm
script:
  - "bash -ex ./travis/run.sh"
